#spring:
#  application:
#    name: config-server

server:
  port: 7001

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/geemu/spring-cloud/
          searchPaths: config-repo
          username: geemu
          password: Boy.cfm*#520.

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
