server:
  port: 8761  # 服务端口

eureka:
  instance:
    hostname: localhost # 设置实例主机名
  client:
    register-with-eureka: false  # 是否向 Eureka 注册服务。服务注册中心服务，没有作为集群，所以不需要自注册，设置为 false
    fetch-registry: false         # 是否检索服务。该应用为服务注册中心，职责为注册和发现服务，无需检索服务，设置为 false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false      # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 5000  # 清理间隔（单位毫秒，默认是60*1000）
    wait-time-in-ms-when-sync-empty: 0   # 设置同步为空时的等待时间。默认 5 * MINUTES